CREATE TABLE `contratos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(255) NOT NULL,
	`genero` varchar(64) NOT NULL,
	`estadoCivil` varchar(64) NOT NULL,
	`profissao` varchar(128) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(20) NOT NULL,
	`naturalidade` varchar(128) NOT NULL,
	`nomePai` varchar(255) NOT NULL,
	`nomeMae` varchar(255) NOT NULL,
	`rua` varchar(255) NOT NULL,
	`quadra` varchar(64),
	`lote` varchar(64),
	`setor` varchar(128),
	`cidade` varchar(128) NOT NULL,
	`estado` varchar(64),
	`cep` varchar(9) NOT NULL,
	`tipoAcao` text NOT NULL,
	`tribunal` varchar(255) NOT NULL,
	`faseProcessual` text NOT NULL,
	`valorTotal` varchar(64) NOT NULL,
	`valorEntrada` varchar(64) NOT NULL,
	`dataEntrada` varchar(10) NOT NULL,
	`numParcelas` int NOT NULL,
	`valorParcela` varchar(64) NOT NULL,
	`dataPrimeiraParcela` varchar(10) NOT NULL,
	`dataContrato` varchar(10) NOT NULL,
	`criadoEm` timestamp NOT NULL DEFAULT (now()),
	`status` enum('pendente','gerada') NOT NULL DEFAULT 'pendente',
	`downloadToken` varchar(64),
	`observacoes` text,
	CONSTRAINT `contratos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `declaracoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(255) NOT NULL,
	`genero` varchar(64) NOT NULL,
	`estadoCivil` varchar(64) NOT NULL,
	`profissao` varchar(128) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(20) NOT NULL,
	`naturalidade` varchar(128) NOT NULL,
	`nomePai` varchar(255) NOT NULL,
	`nomeMae` varchar(255) NOT NULL,
	`rua` varchar(255) NOT NULL,
	`quadra` varchar(64),
	`lote` varchar(64),
	`setor` varchar(128),
	`cidade` varchar(128) NOT NULL,
	`estado` varchar(64),
	`cep` varchar(9) NOT NULL,
	`dataDeclaracao` varchar(10) NOT NULL,
	`criadoEm` timestamp NOT NULL DEFAULT (now()),
	`status` enum('pendente','gerada') NOT NULL DEFAULT 'pendente',
	`downloadToken` varchar(64),
	`observacoes` text,
	CONSTRAINT `declaracoes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `procuracoes_pa` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nomeMenor` varchar(255) NOT NULL,
	`cpfMenor` varchar(14) NOT NULL,
	`dataNascimento` varchar(10) NOT NULL,
	`nome` varchar(255) NOT NULL,
	`genero` varchar(64) NOT NULL,
	`estadoCivil` varchar(64) NOT NULL,
	`profissao` varchar(128) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(20) NOT NULL,
	`naturalidade` varchar(128) NOT NULL,
	`nomePai` varchar(255) NOT NULL,
	`nomeMae` varchar(255) NOT NULL,
	`rua` varchar(255) NOT NULL,
	`quadra` varchar(64),
	`lote` varchar(64),
	`setor` varchar(128),
	`cidade` varchar(128) NOT NULL,
	`estado` varchar(64),
	`cep` varchar(9) NOT NULL,
	`criadoEm` timestamp NOT NULL DEFAULT (now()),
	`status` enum('pendente','gerada') NOT NULL DEFAULT 'pendente',
	`downloadToken` varchar(64),
	`observacoes` text,
	CONSTRAINT `procuracoes_pa_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `procuracoes` ADD `observacoes` text;