CREATE TABLE `procuracoes_weber_ana` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(255) NOT NULL,
	`genero` varchar(64) NOT NULL,
	`estadoCivil` varchar(64) NOT NULL,
	`profissao` varchar(128) NOT NULL,
	`cpf` varchar(14) NOT NULL,
	`rg` varchar(20) NOT NULL,
	`naturalidade` varchar(128) NOT NULL,
	`nomePai` varchar(255) NOT NULL,
	`nomeMae` varchar(255) NOT NULL,
	`rua` varchar(255) NOT NULL,
	`quadra` varchar(64),
	`lote` varchar(64),
	`setor` varchar(128),
	`cidade` varchar(128) NOT NULL,
	`estado` varchar(64),
	`cep` varchar(9) NOT NULL,
	`criadoEm` timestamp NOT NULL DEFAULT (now()),
	`status` enum('pendente','gerada') NOT NULL DEFAULT 'pendente',
	`downloadToken` varchar(64),
	`observacoes` text,
	CONSTRAINT `procuracoes_weber_ana_id` PRIMARY KEY(`id`)
);
